name: Next.js CI Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js
        run: npm run build
      - name: Run Tests
        run: npm test
      - name: Lint code
        run: npm run lint
      - name: Format code
        run: npm run format
